### ISSUE TITLE
GWT compile : classpath error

### ISSUE THREAD

**Issue by Cafeinoman** [nielsbaloe/vertxui#1]
Hi,
when I run examples with Intellij Idea on Linux, I get an error with the GWT compilation : Compiler is not found on the classpath.
Error is solved with the line which add the " character to the classpath.

**Comment by nielsbaloe** [comment]
Hi,
Thanks for your feedback! 
Hmm, I'm curious. What was your fix exactly, turning of that line or tweaking something? Can you share the code? Then I can check it in. Super thanks!,
Niels

**Comment by Cafeinoman** [comment]
Hi,

I just comment the following line on VertxUI.java (219) : 
```java
classpath = Stream.of(classpath.split(sep)).map(c -> "\"" + c + "\"" + sep).reduce("", String::concat);
```
Hope it can help...

**Comment by nielsbaloe** [comment]
Ahh. Super thanks! I've looked up the specs, according to those it should be possible to put quotes around every item. I rewrote it so that it only puts quotes around the whole thing (which should also be fine according to the java specs). I just checked that in. Does that help? Super thanks!!!
