### ISSUE TITLE
Build fails whlie creating javadocs

### ISSUE THREAD

**Issue by jmens** [nielsbaloe/vertxui#5]
Hi, 
just checked out your master branch to compile the 1.01 version. 1.0 doesn't work for me due to the classpath-issue solved a couple of days ago. 
The current 1.01 doesn't build due to an invalid <dd> tag in FigWheelyServer javadocs: 

[ERROR] /home/clemens/git/vertxui/vertxui-core/src/main/java/live/connector/vertxui/server/FigWheelyServer.java:25: error: tag not allowed here: <dd>
[ERROR] * <dd>vertx.eventBus().publish(FigWheely.figNotify, "bla die bla");

mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: [.,.]
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-67-generic", arch: "amd64", family: "unix"

I deleted the tag and just wanted to let you know.

**Comment by nielsbaloe** [comment]
Hi,

Yes I know. It does not compile properly when you do not check out all projects. But that is unavoidable I'm afraid. This single line is the only line that breaks. Please also check out the 1.01 core project, and the build will succeed. 

Thanks!,
Niels
